"""Cantilever identification in dimensionless compliance coordinates.

For this statically determinate system displacement is linear in 1/EI and
clamp compliance. The default influence columns are generated by FEM solves,
then bounded weighted linear least squares is used (no nonlinear optimizer needed).
"""

import csv
import io
from dataclasses import dataclass, field
from functools import lru_cache
from itertools import combinations

import numpy as np
from scipy.optimize import lsq_linear

from .model import ModelError, model_from_dict
from .solver import solve_linear


@dataclass(frozen=True)
class Observation:
    id: str
    x: float
    load_position: float
    force: float
    displacement: float
    sigma: float
    split: str = "train"
    provenance: str = "synthetic"
    run_id: str = "run-1"


@dataclass(frozen=True)
class IdentificationConfig:
    length: float = 1.0
    EI_reference: float = 1000.0
    support_model: str = "flexible"
    bootstrap_samples: int = 200
    seed: int = 2027
    backend: str = "fem"


@dataclass
class IdentificationResult:
    status: str
    provenance: str
    EI: float | None
    clamp_compliance: float | None
    rank: int
    singular_values: list[float]
    correlation: float | None
    predictions: list[float]
    residuals: list[float]
    train_rmse: float | None
    holdout_rmse: float | None
    intervals: dict[str, list[float]] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)


def analytical_deflection(x, a, force, EI, compliance=0.0):
    """Positive downward point load/deflection. Clamp translation is zero."""
    x, a = np.asarray(x), np.asarray(a)
    bending = np.where(x <= a, x * x * (3 * a - x), a * a * (3 * x - a)) / 6
    return force * (bending / EI + a * x * compliance)


@lru_cache(maxsize=2048)
def _fem_columns(length: float, reference: float, x: float, a: float) -> tuple[float, float]:
    coordinates = sorted({0.0, length, x, a})
    ids = {value: str(i) for i, value in enumerate(coordinates)}
    data = {
        "schema_version": 1,
        "units": "N-m-Pa",
        "kind": "beam",
        "nodes": [{"id": ids[v], "x": v} for v in coordinates],
        "materials": [{"id": "m", "E": reference}],
        "sections": [{"id": "s", "A": 1.0, "I": 1.0}],
        "elements": [
            {"id": str(i), "start": ids[left], "end": ids[right], "material": "m", "section": "s"}
            for i, (left, right) in enumerate(zip(coordinates[:-1], coordinates[1:], strict=True))
        ],
        "constraints": [{"node": "0", "dof": "uy"}, {"node": "0", "dof": "rz"}],
        "loads": [{"node": ids[a], "dof": "uy", "value": -1.0}],
    }
    rigid = solve_linear(model_from_dict(data))
    position = rigid.labels.index(f"{ids[x]}:uy")
    u0 = -rigid.displacements[position]
    data["constraints"] = [{"node": "0", "dof": "uy"}]
    data["springs"] = [{"node": "0", "dof": "rz", "stiffness": reference / length}]
    compliant = solve_linear(model_from_dict(data))
    return float(u0), float(-compliant.displacements[position] - u0)


def design_matrix(observations: list[Observation], configuration: IdentificationConfig):
    c = configuration
    rows = []
    for o in observations:
        if c.backend == "fem":
            bending, rotation = _fem_columns(c.length, c.EI_reference, o.x, o.load_position)
            rows.append([o.force * bending, o.force * rotation])
        else:
            bending = float(analytical_deflection(o.x, o.load_position, o.force, c.EI_reference))
            rows.append([bending, o.force * o.load_position * o.x * c.length / c.EI_reference])
    return np.asarray(rows)[:, : 1 if c.support_model == "rigid" else 2]


def _validate_observations(observations, c):
    if (
        not np.isfinite(c.length)
        or c.length <= 0
        or not np.isfinite(c.EI_reference)
        or c.EI_reference <= 0
    ):
        raise ModelError("Length and EI reference must be positive finite SI values.")
    if c.backend not in ("fem", "analytical") or c.support_model not in ("rigid", "flexible"):
        raise ModelError("Choose a supported identification model/backend.")
    if c.bootstrap_samples < 0 or c.bootstrap_samples > 5000:
        raise ModelError("Bootstrap count must be between 0 and 5000.")
    if not observations or len(observations) > 10000:
        raise ModelError("Supply 1–10,000 observations.")
    if len({o.id for o in observations}) != len(observations):
        raise ModelError("Observation IDs must be unique.")
    if len({o.provenance for o in observations}) != 1:
        raise ModelError("Do not mix measured and synthetic observations in a fit.")
    for o in observations:
        if (
            not o.id
            or o.provenance not in ("synthetic", "measured")
            or o.split not in ("train", "holdout")
        ):
            raise ModelError("Each observation needs an ID, provenance and train/holdout split.")
        if not np.all(np.isfinite([o.x, o.load_position, o.force, o.displacement, o.sigma])):
            raise ModelError("Observations must be finite.")
        if not 0 < o.x <= c.length or not 0 < o.load_position <= c.length or o.sigma <= 0:
            raise ModelError(
                "Positions must lie in (0, length]; sigma must be a positive standard uncertainty."
            )
    if not any(o.split == "train" for o in observations):
        raise ModelError("At least one training observation is required.")


def _estimate(A, b):
    # beta = EI_reference/EI > 0; gamma = EI_reference*compliance/length >= 0.
    lower = np.zeros(A.shape[1])
    lower[0] = 1e-12
    result = lsq_linear(A, b, bounds=(lower, np.full(A.shape[1], np.inf)), method="bvls", tol=1e-12)
    if not result.success:
        raise ModelError("Bounded identification failed to converge.")
    return result.x


def fit_cantilever(
    observations: list[Observation], configuration: IdentificationConfig | None = None
) -> IdentificationResult:
    c = configuration or IdentificationConfig()
    _validate_observations(observations, c)
    X = design_matrix(observations, c)
    y = np.array([o.displacement for o in observations])
    sigmas = np.array([o.sigma for o in observations])
    training = np.array([o.split == "train" for o in observations])
    A, b = X[training] / sigmas[training, None], y[training] / sigmas[training]
    singular = np.linalg.svd(A, compute_uv=False)
    rank = int(np.sum(singular > (singular[0] * 1e-10 if singular[0] else 0)))
    if rank < X.shape[1]:
        return IdentificationResult(
            "unidentifiable",
            observations[0].provenance,
            None,
            None,
            rank,
            singular.tolist(),
            None,
            [],
            [],
            None,
            None,
            warnings=[
                "These observations cannot separate beam and clamp flexibility. Change sensor or load positions. Repeating only the load magnitude does not add independent information."
            ],
        )
    beta = _estimate(A, b)
    predictions = X @ beta
    errors = predictions - y
    covariance = np.linalg.pinv(A.T @ A)
    correlation = (
        None
        if len(beta) == 1
        else float(covariance[0, 1] / np.sqrt(covariance[0, 0] * covariance[1, 1]))
    )
    compliance = float(beta[1] * c.length / c.EI_reference) if len(beta) == 2 else 0.0
    notes = [
        "These ranges assume the chosen beam model, exact geometry and loads, and independent Gaussian measurement errors. They do not include unknown systematic errors such as zero drift."
    ]
    if singular[-1] / singular[0] < 1e-3:
        notes.append(
            "The data separate the two parameters only weakly. Treat the estimates with care."
        )
    if beta[0] <= 1e-10:
        notes.append(
            "The fitted inverse beam stiffness reached its numerical lower limit. EI is not reliably determined."
        )
    intervals = {}
    if c.bootstrap_samples:
        rng = np.random.default_rng(c.seed)
        estimates = np.array(
            [
                _estimate(
                    A, (predictions[training] + rng.normal(0, sigmas[training])) / sigmas[training]
                )
                for _ in range(c.bootstrap_samples)
            ]
        )
        intervals["EI_N_m2"] = np.percentile(c.EI_reference / estimates[:, 0], [2.5, 97.5]).tolist()
        if len(beta) == 2:
            ci = np.percentile(estimates[:, 1] * c.length / c.EI_reference, [2.5, 97.5]).tolist()
            intervals["clamp_compliance_rad_per_Nm"] = ci
            if ci[0] <= 1e-15 * c.length / c.EI_reference:
                notes.append(
                    "Clamp compliance is indistinguishable from zero with this data quality. Report the compliance range, not a precise spring stiffness."
                )
    if not np.any(~training):
        notes.append(
            "No observations were reserved for prediction checks. The fit was checked only on its training data."
        )
    return IdentificationResult(
        "identified",
        observations[0].provenance,
        float(c.EI_reference / beta[0]),
        compliance,
        rank,
        singular.tolist(),
        correlation,
        predictions.tolist(),
        errors.tolist(),
        float(np.sqrt(np.mean(errors[training] ** 2))),
        float(np.sqrt(np.mean(errors[~training] ** 2))) if np.any(~training) else None,
        intervals,
        notes,
    )


def select_measurement_positions(
    length: float,
    candidates: list[float],
    count: int,
    loads: list[tuple[float, float]],
    EI_reference: float,
):
    """Exhaustive E-optimal subset, fixed dimensionless parameter scaling; no data leakage."""
    if not 1 <= count <= len(candidates) or len(candidates) > 12:
        raise ModelError("Select a valid subset of at most 12 candidate locations.")
    config = IdentificationConfig(length, EI_reference, backend="analytical", bootstrap_samples=0)
    best, score = None, -1.0
    for subset in combinations(candidates, count):
        obs = [
            Observation(str(i), x, a, force, 0.0, 1.0)
            for i, (x, a, force) in enumerate((x, a, f) for x in subset for a, f in loads)
        ]
        _validate_observations(obs, config)
        A = design_matrix(obs, config)
        singular = np.linalg.svd(A, compute_uv=False)
        current = float(singular[-1]) if len(singular) == 2 else 0.0
        if current > score:
            best, score = subset, current
    return list(best or []), score


CSV_COLUMNS = [
    "id",
    "x_m",
    "load_position_m",
    "force_N",
    "raw_displacement_m",
    "zero_m",
    "sigma_m",
    "split",
    "provenance",
    "run_id",
]


def observations_csv(observations: list[Observation]) -> str:
    out = io.StringIO(newline="")
    writer = csv.writer(out)
    writer.writerow(CSV_COLUMNS)
    for o in observations:
        writer.writerow(
            [
                o.id,
                o.x,
                o.load_position,
                o.force,
                o.displacement,
                0.0,
                o.sigma,
                o.split,
                o.provenance,
                o.run_id,
            ]
        )
    return out.getvalue()


def read_observations_csv(text: str) -> list[Observation]:
    reader = csv.DictReader(io.StringIO(text.lstrip("\ufeff")))
    if reader.fieldnames != CSV_COLUMNS:
        raise ModelError("CSV columns must match the downloadable SI measurement template exactly.")
    result = []
    try:
        for row in reader:
            result.append(
                Observation(
                    row["id"],
                    float(row["x_m"]),
                    float(row["load_position_m"]),
                    float(row["force_N"]),
                    float(row["raw_displacement_m"]) - float(row["zero_m"]),
                    float(row["sigma_m"]),
                    row["split"],
                    row["provenance"],
                    row["run_id"],
                )
            )
            if len(result) > 10000:
                raise ModelError("Measurement CSV exceeds 10,000 rows.")
    except (KeyError, TypeError, ValueError) as exc:
        raise ModelError(f"Invalid measurement row: {exc}") from exc
    return result


def validate_measurement_metadata(metadata: dict, length: float) -> None:
    """Require a usable provenance record; metadata templates are not evidence."""
    if not isinstance(metadata, dict) or metadata.get("provenance") != "measured":
        raise ModelError("Metadata must explicitly declare measured provenance.")
    try:
        specimen, fixture, instrument = (
            metadata["specimen"],
            metadata["fixture"],
            metadata["instrument"],
        )
        for value in (
            specimen["free_length_m"],
            specimen["width_m"],
            specimen["depth_m"],
            instrument["resolution_m"],
        ):
            if (
                isinstance(value, bool)
                or not isinstance(value, (int, float))
                or not np.isfinite(value)
                or value <= 0
            ):
                raise ModelError(
                    "Specimen dimensions and instrument resolution must be positive measured numbers."
                )
        if not np.isclose(specimen["free_length_m"], length, rtol=1e-6, atol=1e-9):
            raise ModelError("Fit length does not match the specimen metadata.")
        required = [
            specimen["description"],
            fixture["description"],
            fixture["translation_check"],
            instrument["description"],
            instrument["calibration_record"],
            metadata["load_calibration"],
            metadata["uncertainty_method"],
        ]
        if any(not isinstance(v, str) or not v.strip() for v in required):
            raise ModelError(
                "Complete specimen, fixture, calibration and uncertainty descriptions before analysis."
            )
    except (KeyError, TypeError) as exc:
        raise ModelError("Metadata must follow the specimen/fixture/instrument template.") from exc
